// <auto-generated />
using MeticulousMentoring.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MeticulousMentoring.API.Migrations
{
    [DbContext(typeof(MeticulousContext))]
    [Migration("20171117165732_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address1");

                    b.Property<string>("address2");

                    b.Property<int>("address_type");

                    b.Property<string>("city");

                    b.Property<DateTime?>("created_on");

                    b.Property<DateTime?>("modified_on");

                    b.Property<string>("state");

                    b.Property<string>("zip");

                    b.HasKey("id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Classification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("classification_id");

                    b.Property<DateTime?>("created_on");

                    b.Property<string>("description");

                    b.Property<DateTime?>("modified_on");

                    b.HasKey("id");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.EducationSystem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("system");

                    b.HasKey("id");

                    b.ToTable("EducationSystem");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Guardian", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("addressid");

                    b.Property<DateTime?>("created_on");

                    b.Property<string>("email");

                    b.Property<string>("first_name");

                    b.Property<string>("gender");

                    b.Property<string>("last_name");

                    b.Property<string>("middle");

                    b.Property<DateTime?>("modified_on");

                    b.HasKey("id");

                    b.HasIndex("addressid");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Mentee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Guardianid");

                    b.Property<int?>("Mentorid");

                    b.Property<int?>("addressid");

                    b.Property<int?>("classificationid");

                    b.Property<DateTime?>("created_on");

                    b.Property<DateTime>("dob");

                    b.Property<string>("email");

                    b.Property<string>("first_name");

                    b.Property<string>("gender");

                    b.Property<bool>("is_active");

                    b.Property<string>("last_name");

                    b.Property<string>("middle");

                    b.Property<DateTime?>("modified_on");

                    b.Property<int?>("schoolid");

                    b.HasKey("id");

                    b.HasIndex("Guardianid");

                    b.HasIndex("Mentorid");

                    b.HasIndex("addressid");

                    b.HasIndex("classificationid");

                    b.HasIndex("schoolid");

                    b.ToTable("Mentees");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Mentor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("addressid");

                    b.Property<DateTime?>("created_on");

                    b.Property<string>("first_name");

                    b.Property<string>("gender");

                    b.Property<bool>("is_active");

                    b.Property<string>("last_name");

                    b.Property<DateTime?>("modified_on");

                    b.HasKey("id");

                    b.HasIndex("addressid");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.School", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("addressid");

                    b.Property<DateTime?>("created_on");

                    b.Property<DateTime?>("modified_on");

                    b.Property<string>("principal");

                    b.Property<string>("school_name");

                    b.Property<int?>("systemid");

                    b.HasKey("id");

                    b.HasIndex("addressid");

                    b.HasIndex("systemid");

                    b.ToTable("School");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Guardian", b =>
                {
                    b.HasOne("MeticulousMentoring.API.Data.Entities.Address", "address")
                        .WithMany()
                        .HasForeignKey("addressid");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Mentee", b =>
                {
                    b.HasOne("MeticulousMentoring.API.Data.Entities.Guardian")
                        .WithMany("children")
                        .HasForeignKey("Guardianid");

                    b.HasOne("MeticulousMentoring.API.Data.Entities.Mentor")
                        .WithMany("mentees")
                        .HasForeignKey("Mentorid");

                    b.HasOne("MeticulousMentoring.API.Data.Entities.Address", "address")
                        .WithMany()
                        .HasForeignKey("addressid");

                    b.HasOne("MeticulousMentoring.API.Data.Entities.Classification", "classification")
                        .WithMany()
                        .HasForeignKey("classificationid");

                    b.HasOne("MeticulousMentoring.API.Data.Entities.School", "school")
                        .WithMany()
                        .HasForeignKey("schoolid");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.Mentor", b =>
                {
                    b.HasOne("MeticulousMentoring.API.Data.Entities.Address", "address")
                        .WithMany()
                        .HasForeignKey("addressid");
                });

            modelBuilder.Entity("MeticulousMentoring.API.Data.Entities.School", b =>
                {
                    b.HasOne("MeticulousMentoring.API.Data.Entities.Address", "address")
                        .WithMany()
                        .HasForeignKey("addressid");

                    b.HasOne("MeticulousMentoring.API.Data.Entities.EducationSystem", "system")
                        .WithMany()
                        .HasForeignKey("systemid");
                });
#pragma warning restore 612, 618
        }
    }
}
